### ISSUE TITLE
Upgrade to doctrine/dbal 3

### ISSUE THREAD

**Issue by erik-zicht** [zicht/url-bundle#81]
https://github.com/doctrine/dbal/blob/3.1.x/UPGRADE.md

M.n. het gebruik van de `fetch...` methoden.

En ook https://github.com/doctrine/dbal/blob/3.3.x/UPGRADE.md#bc-break-changes-in-fetching-statement-results

**Comment by 7ochem** [comment]
+1 

Een hele brei van Doctrine packages worden in updates tegen gehouden door deze restrictie.
